# Site settings
title: Reshef
description: "Just a landing page for my main domain"
baseurl: "/"
url: "https://reshef.eu.org/"

# User settings
username: Oren Reshef
user_description: "Software Engineer"
user_title: Quality Engineer
email: 

exclude: ['package.json', 'src', 'node_modules', 'vendor']
